### ISSUE TITLE
dump of speed limited card

### ISSUE THREAD

**Issue by rushxrushx** [cyrozap/jmb58x-re#3]
I have a N5095 board with two jmb585 onboard, N5095 support pcie gen3, but the card run at gen2, I try to desolder the spi rom, with internal firmware, the card can run at gen3, work fine with some 64G ssd,but if connect sandisk 2T ssd, it hang at boot. here is my dump. dump offline by programmer.
https://github.com/rushxrushx/jmb585_dump
this ROM is 00.01.01.20, it seems to be newest version on the net.

![IMG_20240420_190908](https://github.com/cyrozap/jmb58x-re/assets/44940480/72538194-43e0-44cf-8dc4-3caebd233e8d)

**Comment by cyrozap** [comment]
Thank you, that flash dump is very interesting. I used `tools/parse.py -c` to parse both a flash dump I took from an IOCrest IO-M2F585-5I and one of the dumps you made from the your N5095 board, then diffed the parsed configurations:

```diff
--- flash_IO-M2F585-5I.bin.txt	2024-04-27 16:12:58.497860176 -0500
+++ jmb585-dump01.BIN.txt	2024-04-27 16:13:21.474432178 -0500
@@ -11,26 +11,26 @@
 0x03060010  |  0x01f800b8  [ 0000 0001 11111 000000000 0010 1110 00 ]  [ 0x0 0x1 0x1f 0x0 0x2 0xe 0x0 ]  |  BAR5[0x00b8] <= 0x03060010
 0xf9e4ffbf  |  0x01f800b0  [ 0000 0001 11111 000000000 0010 1100 00 ]  [ 0x0 0x1 0x1f 0x0 0x2 0xc 0x0 ]  |  BAR5[0x00b0] <= 0xf9e4ffbf
 0x0028ff00  |  0x02f80241  [ 0000 0010 11111 000000000 1001 0000 01 ]  [ 0x0 0x2 0x1f 0x0 0x9 0x0 0x1 ]
-0x0086c005  |  0x02f80024  [ 0000 0010 11111 000000000 0000 1001 00 ]  [ 0x0 0x2 0x1f 0x0 0x0 0x9 0x0 ]
 0x00560010  |  0x04f80378  [ 0000 0100 11111 000000000 1101 1110 00 ]  [ 0x0 0x4 0x1f 0x0 0xd 0xe 0x0 ]
 0x00560010  |  0x04f80778  [ 0000 0100 11111 000000001 1101 1110 00 ]  [ 0x0 0x4 0x1f 0x1 0xd 0xe 0x0 ]
 0x000d021c  |  0x04f8001c  [ 0000 0100 11111 000000000 0000 0111 00 ]  [ 0x0 0x4 0x1f 0x0 0x0 0x7 0x0 ]
 0x00120010  |  0x04f804d8  [ 0000 0100 11111 000000001 0011 0110 00 ]  [ 0x0 0x4 0x1f 0x1 0x3 0x6 0x0 ]
-0x22015f00  |  0x04f804f8  [ 0000 0100 11111 000000001 0011 1110 00 ]  [ 0x0 0x4 0x1f 0x1 0x3 0xe 0x0 ]
-0x00000002  |  0x04f804fc  [ 0000 0100 11111 000000001 0011 1111 00 ]  [ 0x0 0x4 0x1f 0x1 0x3 0xf 0x0 ]
+0x10040000  |  0x04f804f8  [ 0000 0100 11111 000000001 0011 1110 00 ]  [ 0x0 0x4 0x1f 0x1 0x3 0xe 0x0 ]
+0x00000000  |  0x04f804fc  [ 0000 0100 11111 000000001 0011 1111 00 ]  [ 0x0 0x4 0x1f 0x1 0x3 0xf 0x0 ]
 0x00120010  |  0x04f80518  [ 0000 0100 11111 000000001 0100 0110 00 ]  [ 0x0 0x4 0x1f 0x1 0x4 0x6 0x0 ]
-0x22015f00  |  0x04f80538  [ 0000 0100 11111 000000001 0100 1110 00 ]  [ 0x0 0x4 0x1f 0x1 0x4 0xe 0x0 ]
-0x00000002  |  0x04f8053c  [ 0000 0100 11111 000000001 0100 1111 00 ]  [ 0x0 0x4 0x1f 0x1 0x4 0xf 0x0 ]
+0x10040000  |  0x04f80538  [ 0000 0100 11111 000000001 0100 1110 00 ]  [ 0x0 0x4 0x1f 0x1 0x4 0xe 0x0 ]
+0x00000000  |  0x04f8053c  [ 0000 0100 11111 000000001 0100 1111 00 ]  [ 0x0 0x4 0x1f 0x1 0x4 0xf 0x0 ]
 0x48bc3089  |  0x04f8002c  [ 0000 0100 11111 000000000 0000 1011 00 ]  [ 0x0 0x4 0x1f 0x0 0x0 0xb 0x0 ]
 0x48bc3089  |  0x04f8042c  [ 0000 0100 11111 000000001 0000 1011 00 ]  [ 0x0 0x4 0x1f 0x1 0x0 0xb 0x0 ]
-0x00005f0e  |  0x04f80170  [ 0000 0100 11111 000000000 0101 1100 00 ]  [ 0x0 0x4 0x1f 0x0 0x5 0xc 0x0 ]
-0x00005f0e  |  0x04f80570  [ 0000 0100 11111 000000001 0101 1100 00 ]  [ 0x0 0x4 0x1f 0x1 0x5 0xc 0x0 ]
+0x00005f04  |  0x04f80170  [ 0000 0100 11111 000000000 0101 1100 00 ]  [ 0x0 0x4 0x1f 0x0 0x5 0xc 0x0 ]
+0x00005f04  |  0x04f80570  [ 0000 0100 11111 000000001 0101 1100 00 ]  [ 0x0 0x4 0x1f 0x1 0x5 0xc 0x0 ]
 0x00000007  |  0x04f8100d  [ 0000 0100 11111 000000100 0000 0011 01 ]  [ 0x0 0x4 0x1f 0x4 0x0 0x3 0x1 ]
+0x000f4000  |  0x04f800e0  [ 0000 0100 11111 000000000 0011 1000 00 ]  [ 0x0 0x4 0x1f 0x0 0x3 0x8 0x0 ]
 0x00001010  |  0x04f800e4  [ 0000 0100 11111 000000000 0011 1001 00 ]  [ 0x0 0x4 0x1f 0x0 0x3 0x9 0x0 ]
 0x40454e9b  |  0x04f800e8  [ 0000 0100 11111 000000000 0011 1010 00 ]  [ 0x0 0x4 0x1f 0x0 0x3 0xa 0x0 ]
 0x003c0000  |  0x04f800d4  [ 0000 0100 11111 000000000 0011 0101 00 ]  [ 0x0 0x4 0x1f 0x0 0x3 0x5 0x0 ]
 0x00ff00ff  |  0x04f800d8  [ 0000 0100 11111 000000000 0011 0110 00 ]  [ 0x0 0x4 0x1f 0x0 0x3 0x6 0x0 ]
-0x00015000  |  0x04f800dc  [ 0000 0100 11111 000000000 0011 0111 00 ]  [ 0x0 0x4 0x1f 0x0 0x3 0x7 0x0 ]
+0x00012800  |  0x04f800dc  [ 0000 0100 11111 000000000 0011 0111 00 ]  [ 0x0 0x4 0x1f 0x0 0x3 0x7 0x0 ]
 0x00000001  |  0x04f81031  [ 0000 0100 11111 000000100 0000 1100 01 ]  [ 0x0 0x4 0x1f 0x4 0x0 0xc 0x1 ]
 0x20d0800f  |  0x04f800b0  [ 0000 0100 11111 000000000 0010 1100 00 ]  [ 0x0 0x4 0x1f 0x0 0x2 0xc 0x0 ]
 0x20d0800f  |  0x04f804b0  [ 0000 0100 11111 000000001 0010 1100 00 ]  [ 0x0 0x4 0x1f 0x1 0x2 0xc 0x0 ]
@@ -336,6 +336,7 @@
 0x000210f0  |  0x04f8045c  [ 0000 0100 11111 000000001 0001 0111 00 ]  [ 0x0 0x4 0x1f 0x1 0x1 0x7 0x0 ]
 0x0002250b  |  0x04f80030  [ 0000 0100 11111 000000000 0000 1100 00 ]  [ 0x0 0x4 0x1f 0x0 0x0 0xc 0x0 ]
 0x0002250b  |  0x04f80430  [ 0000 0100 11111 000000001 0000 1100 00 ]  [ 0x0 0x4 0x1f 0x1 0x0 0xc 0x0 ]
+0x000000a1  |  0x04f81000  [ 0000 0100 11111 000000100 0000 0000 00 ]  [ 0x0 0x4 0x1f 0x4 0x0 0x0 0x0 ]
 0x00000024  |  0x04fc007c  [ 0000 0100 11111 100000000 0001 1111 00 ]  [ 0x0 0x4 0x1f 0x100 0x1 0xf 0x0 ]
 0x250b0003  |  0x04fc0086  [ 0000 0100 11111 100000000 0010 0001 10 ]  [ 0x0 0x4 0x1f 0x100 0x2 0x1 0x2 ]
 0x00000024  |  0x04fc0078  [ 0000 0100 11111 100000000 0001 1110 00 ]  [ 0x0 0x4 0x1f 0x100 0x1 0xe 0x0 ]
@@ -373,4 +374,4 @@
 0x00000000  |  0x01f8032c  [ 0000 0001 11111 000000000 1100 1011 00 ]  [ 0x0 0x1 0x1f 0x0 0xc 0xb 0x0 ]  |  BAR5[0x032c] <= 0x00000000
 0x03060013  |  0x01f800b8  [ 0000 0001 11111 000000000 0010 1110 00 ]  [ 0x0 0x1 0x1f 0x0 0x2 0xe 0x0 ]  |  BAR5[0x00b8] <= 0x03060013
 0x00000c00  |  0x08f80c00  [ 0000 1000 11111 000000011 0000 0000 00 ]  [ 0x0 0x8 0x1f 0x3 0x0 0x0 0x0 ]  |  Option ROM offset: 0x00000c00
-Header version: 0.0.0.21
+Header version: 0.1.1.20
```

After looking at that diff, I think I may have identified the instructions that set the "Supported Link Speeds Vector" field in the "Link Capabilities 2 Register" in the "PCI Express Capability Structure". Specifically, I believe these lines are responsible:

```diff
-0x00005f0e  |  0x04f80170  [ 0000 0100 11111 000000000 0101 1100 00 ]  [ 0x0 0x4 0x1f 0x0 0x5 0xc 0x0 ]
-0x00005f0e  |  0x04f80570  [ 0000 0100 11111 000000001 0101 1100 00 ]  [ 0x0 0x4 0x1f 0x1 0x5 0xc 0x0 ]
+0x00005f04  |  0x04f80170  [ 0000 0100 11111 000000000 0101 1100 00 ]  [ 0x0 0x4 0x1f 0x0 0x5 0xc 0x0 ]
+0x00005f04  |  0x04f80570  [ 0000 0100 11111 000000001 0101 1100 00 ]  [ 0x0 0x4 0x1f 0x1 0x5 0xc 0x0 ]
```

Of note is that the data value for each instruction changes from "0x00005f0e" in the IO-M2F585-5I's configuration to "0x00005f04" in your device's configuration, and the bits that are cleared in that value in your device's configuration correspond to the bits in the "Supported Link Speeds Vector" that represent 8.0 GT/s and 2.5 GT/s. Since you said that when the flash is connected on your device the JMB585 chips only link at 5.0 GT/s (PCIe Gen2 speed), it stands to reason that the lowest eight bits in that data field for those two instructions correspond to the lowest eight bits in the "Link Capabilities 2 Register". I'll have to perform some tests to confirm if this is true.

**Comment by rushxrushx** [comment]
I use hex  editor to find '04 5f 00 00' in dump.bin , there are 2 occur, I replace them with '0e 5f 00 00', and flash them back, nothing happed, hwinfo says it 5GT/s nothing changed.

**Comment by cyrozap** [comment]
Sorry about that--I probably should have tested that myself before suggesting that it might be what affects the link speed.

I've since performed some testing and found the actual instruction that sets the link speed. It's this one:

```diff
+0x000000a1  |  0x04f81000  [ 0000 0100 11111 000000100 0000 0000 00 ]  [ 0x0 0x4 0x1f 0x4 0x0 0x0 0x0 ]
```

That configures the max link speed to 5 GT/s and max link width to x1.

After further testing, I found that changing the data value for that instruction from `0x000000a1` to `0x000000a2` sets the reported max link speed to 8 GT/s, but keeps the max link width at x1. Setting the value to `0x000000a6` configures the max link speed to 8 GT/s and max link width to x2 (the default). And after even more testing I found that the rule is as follows: Bits 0 and 1 of that value control the max link speed (0: 2.5 GT/s, 1: 5 GT/s, 2: 8 GT/s, 3: 16 GT/s (please note that setting this value to 3 only sets the max speed in the LnkCap register to 16 GT/s and does not add the 16 GT/s link speed to the Supported Link Speeds Vector in LnkCap2)), and bit 2 controls the max link width (0: x1, 1: x2). I have yet to determine the functions of bits 3-7.

So, to change that value in your flash image and make the chip report that it supports 8 GT/s speeds (without changing the max link width), you would need to set the byte at address `0x00000A8C` in the image from `0xa1` to `0xa2`.

**Comment by rushxrushx** [comment]
It works! note: card should be power down to make new fw take effect. Only reboot is not enough. 
![无标题](https://github.com/cyrozap/jmb58x-re/assets/44940480/390e9823-b78a-4dbf-9280-85ca6def6f32)

**Comment by rushxrushx** [comment]
Thanks for your work!

**Comment by cyrozap** [comment]
Great, I'm glad to hear it worked! One thing I should mention though is that the system manufacturer probably had a reason to configure the JMB585 chips to both run at 5 GT/s. For example, the link speeds may have been reduced for signal integrity reasons, so you may want to monitor your system for issues like link training failures (the link should drop down to a slower speed if that happens), data integrity issues (you may see data corruption on SATA drives connected to the JMB585 chips with the 8 GT/s configuration), and crashes (if there is data corruption on the link and it isn't caught by the PCIe data link layer checksum, it could cause bad DMA writes to be sent to the host or bad DMA reads of commands by the JMB585, resulting in driver or OS crashes).
